### ISSUE TITLE
How fitness helps you become a better developer

### ISSUE THREAD

**Issue by mykiwi** [SymfonyCon/2019-talks#14]
Hello @magnusnordlander,
Could you share your slides please ?
Thank you

**Comment by magnusnordlander** [comment]
Sure, slides are attached.
[Fitness.pdf](https://github.com/SymfonyCon/2019-talks/files/3944384/Fitness.pdf)

**Comment by mykiwi** [comment]
Thank you @magnusnordlander :+1:
