### ISSUE TITLE
Eeek, my tests are mutating!

### ISSUE THREAD

**Issue by mykiwi** [SymfonyCon/2019-talks#15]
Hello @Landerstraeten,
Could you share your slides please ?
Thank you

**Comment by Landerstraeten** [comment]
Hello,

Sorry for my late answer. You can find my slides online at https://landerstraeten.github.io/#/

Kind regards,
Lander

On 5 Dec 2019, at 09:30, Romain Gautier <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello @Landerstraeten<https://github.com/Landerstraeten>,
Could you share your slides please ?
Thank you

**Comment by mykiwi** [comment]
Thank you @Landerstraeten
